import images from '../assets/images';
import {
  AboutOtrade_Icon,
  AvgVolumeIcon,
  BuySharesIcon,
  CloseYourAccount_Icon,
  DarkMode_Icon,
  DepositToOtrade,
  DividendYieldIcon,
  ExchangeStockIcon,
  FinancialTransaction,
  FundingActivity,
  HelpCenter_Icon,
  HighIcon,
  Language_Icon,
  LegalAgreements_Icon,
  Logout_Icon,
  LowIcon,
  MarketCapIcon,
  NotificationIcon1,
  NotificationIcon2,
  NotificationIcon3,
  NotificationIcon4,
  NotificationIcon5,
  NotificationIcon6,
  Notification_Icon,
  PaymentMethods,
  PersonalInfo_Icon,
  PriceEarningsRatioIcon,
  Security_Icon,
  WithdrawFromOtrade,
} from '../assets/svgs';
import { moderateScale } from '../common/constants';
import strings from '../i18n/strings';
import { StackNav } from '../navigation/NavigationKeys';

const commonWH = moderateScale(72);

const GenderData = [
  { label: 'I am male', value: 'I am male' },
  { label: 'I am female', value: 'I am female' },
];

const ProfileSetting = [
  {
    id: 10,
    title: strings.developerSettings,
    icon: <DarkMode_Icon />, // Vous devrez ajouter cette icône
    route: StackNav.DeveloperSettings,
  },
  /*
  {
    id: 1,
    title: strings.personalInfo,
    icon: <PersonalInfo_Icon />,
    route: StackNav.PersonalInfo,
    header: strings.editProfile,
  },
  {
    id: 2,
    title: strings.notification,
    icon: <Notification_Icon />,
    route: StackNav.NotificationSetting,
  },
  {
    id: 4,
    title: strings.security,
    icon: <Security_Icon />,
    route: StackNav.Security,
  },
  */
  {
    id: 5,
    title: strings.language,
    icon: <Language_Icon />,
    value: 'English(US)',
    route: StackNav.Language,
  },
  {
    id: 6,
    title: strings.darkMode,
    icon: <DarkMode_Icon />,
    rightIcon: 'rightIcon',
  },
  /*
  {
    id: 2,
    title: strings.address,
    icon: <Notification_Icon />,
    route: StackNav.Address,
  },
  {
    id: 8,
    title: strings.helpCenter,
    icon: <HelpCenter_Icon />,
    route: StackNav.HelpCenter,
  },
  {
    id: 3,
    title: strings.legalAgreements,
    icon: <LegalAgreements_Icon />,
    // route: StackNav.Payment,
  },
  */
  {
    id: 7,
    title: strings.aboutLittleJohn,
    icon: <AboutOtrade_Icon />,
    route: StackNav.AboutOtrade,
  },
  {
    id: 8,
    title: strings.closeYourAccount,
    icon: <CloseYourAccount_Icon />,
    // route: StackNav.InviteFriends,
    isRightIcon: true,
  },
  {
    id: 9,
    title: strings.logout,
    icon: <Logout_Icon />,
    route: StackNav.InviteFriends,
    isRightIcon: true,
    isLogout: true,
  },

];

const question5Data = [
  'I want to grow my capital',
  'I want to speculate',
  'I want to hedge',
  'I want to learn investments',
  "I still don't know for sure",
];

const yesAndNoData = ['Yes', 'No'];

const WorkTypeData = [
  'I’m employed',
  'I’m a professional',
  'I’m a student',
  'I’m a housewife',
  'I’m a freelancer',
  'I’m a business owner',
  'I’m retired',
  'I’m unemployed',
];

const countryData = [
  { label: 'United States', value: 'United States' },
  { label: 'United Kingdom', value: 'United Kingdom' },
  { label: 'Australia', value: 'Australia' },
  { label: 'Canada', value: 'Canada' },
  { label: 'France', value: 'France' },
  { label: 'Germany', value: 'Germany' },
  { label: 'Italy', value: 'Italy' },
  { label: 'Japan', value: 'Japan' },
  { label: 'Russia', value: 'Russia' },
  { label: 'South Korea', value: 'South Korea' },
  { label: 'Spain', value: 'Spain' },
  { label: 'Switzerland', value: 'Switzerland' },
  { label: 'China', value: 'China' },
  { label: 'Brazil', value: 'Brazil' },
  { label: 'Mexico', value: 'Mexico' },
  { label: 'Argentina', value: 'Argentina' },
  { label: 'Indonesia', value: 'Indonesia' },
  { label: 'Turkey', value: 'Turkey' },
  { label: 'Netherlands', value: 'Netherlands' },
];

const houseStatusData = [
  'I own my house',
  'I rent my house',
  'I live with my friends',
  'I live with my family',
  'I live with my relatives',
  "My mother-in-law's house",
  'Other',
];

const termsAndConditionData = [
  'I certify that I am a national of the United States of America.',
  'I am not currently or formerly a politically exposed person or public official.',
  'I am not working at and do not have family members working at Invest.',
  'I have read, understood and agree to be bound by all terms, disclosures, certifications, and disclaimers applicable to me, as found on the legal page of the Invest website.',
];

const inviteFriendData = [
  {
    id: 1,
    title: strings.inviteYourFriends,
    desc: strings.inviteYourFriendsDesc,
    termAndCond: false,
  },
  {
    id: 2,
    title: strings.theyGetFreeStock,
    desc: strings.theyGetFreeStockDesc,
    termAndCond: true,
  },
  {
    id: 3,
    title: strings.youGetFreeStock,
    desc: strings.youGetFreeStockDesc,
    termAndCond: true,
  },
];

const myRewardsData = [
  {
    id: 1,
    image: images.user1,
    name: 'Andrew Ainsley',
    earning: '$10',
  },
  {
    id: 2,
    image: images.user2,
    name: 'Samantha Smith',
    earning: '$5',
  },
  {
    id: 3,
    image: images.user3,
    name: 'Franklin Jones',
    earning: '$5',
  },
  {
    id: 4,
    image: images.user4,
    name: 'Emma Smith',
    earning: '$3',
  },
  {
    id: 5,
    image: images.user5,
    name: 'George Smith',
    earning: '$15',
  },
  {
    id: 6,
    image: images.user6,
    name: 'David Smith',
    earning: '$2',
  },
];

const contactUsData = [
  {
    id: 1,
    title: 'Customer Service',
    icon: 'headset',
  },
  {
    id: 2,
    title: 'WhatsApp',
    icon: 'whatsapp',
  },
  {
    id: 3,
    title: 'Website',
    icon: 'google-earth',
  },
  {
    id: 4,
    title: 'Facebook',
    icon: 'facebook',
  },
  {
    id: 5,
    title: 'Instagram',
    icon: 'instagram',
  },
  {
    id: 6,
    title: 'Twitter',
    icon: 'twitter',
  },
];

const helperCategoryData = [
  'General',
  'Account',
  'Payment',
  'Subscription',
  'Others',
];

const helperData = [
  {
    title: 'What is Invest?',
    description:
      'Anistream is a streaming service that offers a wide variety of anime titles.',
  },
  {
    title: 'How to use Invest?',
    description:
      'You can sign up for Anistream by downloading the app from the App Store or Google Play Store.',
  },
  {
    title: 'How do I cancel a orders product?',
    description:
      'You can remove anime on your wishlist by clicking the heart icon on the anime details page.',
  },
  {
    title: 'Is Invest free to use?',
    description:
      'You can subscribe to premium by clicking the premium button on the home page.',
  },
  {
    title: 'How to add promo on Invest?',
    description:
      'You can download anime by clicking the download icon on the anime details page.',
  },
  {
    title: 'How to unsubscribe from premium?',
    description:
      'You can unsubscribe from premium by clicking the premium button on the home page.',
  },
];

const languageData = [
  {
    title: 'Suggested',
    data: [{ lnName: 'English(US)' }, { lnName: 'English(UK)' }],
  },
  {
    title: 'Language',
    data: [
      {
        lnName: 'English',
      },
      {
        lnName: 'Spanish',
      },
      {
        lnName: 'French',
      },
      {
        lnName: 'German',
      },
      {
        lnName: 'Italian',
      },
      {
        lnName: 'Portuguese',
      },
      {
        lnName: 'Russian',
      },
      {
        lnName: 'Turkish',
      },
      {
        lnName: 'Chinese',
      },
      {
        lnName: 'Japanese',
      },
      {
        lnName: 'Korean',
      },
      {
        lnName: 'Arabic',
      },
      {
        lnName: 'Hindi',
      },
      {
        lnName: 'Indonesian',
      },
      {
        lnName: 'Malay',
      },
      {
        lnName: 'Thai',
      },
    ],
  },
];

const aboutOtradeData = [
  'Job Vacancy',
  'Fees',
  'Partner',
  'Developer',
  'Blog',
  'Terms & Conditions',
  'Privacy Policy',
  'FAQ',
  'Contact Us',
  'Visit Our Website',
  'Follow us on Social Media',
];

const moreData = [
  {
    id: 1,
    title: 'Exchange Stocks',
    icon: <ExchangeStockIcon />,
    desc: 'Exchange your stock from one company to another',
    route: StackNav.ExchangeStock,
  },
  {
    id: 2,
    title: 'Transfer Assets',
    icon: <ExchangeStockIcon />,
    desc: 'Send your assets to another wallet or address',
    route: StackNav.TransferEntry,
  },
  {
    id: 3,
    title: 'Deposit to Invest',
    icon: <DepositToOtrade />,
    desc: 'Transfer funds instantly to your Invest account',
    // route: StackNav.DepositToOtrade,
    route: StackNav.IncommingFeature, // Redirigé vers la page Coming Soon
  },
  /*
  {
    id: 3,
    title: 'Withdraw from Invest',
    icon: <WithdrawFromOtrade />,
    desc: 'Transfer money from your Invest account to your bank',
    route: StackNav.WithdrawalAccount,
  },
  {
    id: 3,
    title: 'Funding Activity',
    icon: <FundingActivity />,
    desc: 'Your historical & live fund details in and out of Invest',
    route: StackNav.FundingActivity,
  },
  */
  {
    id: 4,
    title: 'Financial Transaction',
    icon: <FinancialTransaction />,
    desc: 'History of your stock transactions in the Invest stock market',
    route: StackNav.FinancialTransaction,
  },
  /*
  {
    id: 3,
    title: 'Payment Methods',
    icon: <PaymentMethods />,
    desc: 'Other connected payment methods other than banks',
    route: StackNav.PaymentMethods,
  },
  */
];

const listedStockData = [
  {
    value: '1',
    lable: 'Spotify',
    image: images.spotifyIcon,
  },
  {
    value: '2',
    lable: 'Coco Cola',
    image: images.cocoColaIcon,
  },
  {
    value: '3',
    lable: 'Amazon',
    image: images.amazonIcon,
  },
  {
    value: '4',
    lable: 'Google',
    image: images.googleIcon,
  },
  {
    value: '5',
    lable: 'Meta',
    image: images.metaIcon,
  },
  {
    value: '6',
    lable: 'Macdonalds',
    image: images.macdonaldsIcon,
  },
  {
    value: '7',
    lable: 'Nike',
    image: images.nikeIcon,
  },
  {
    value: '8',
    lable: 'Starbucks',
    image: images.starbucksIcon,
  },
  {
    value: '9',
    lable: 'Tesla',
    image: images.teslaIcon,
  },
  {
    value: '10',
    lable: 'Airbnb',
    image: images.airbnbIcon,
  },
  {
    value: '11',
    lable: 'Netflix',
    image: images.netflixIcon,
  },
];

const depositOtradeData = [
  {
    title: 'Connected Payment Methods',
    data: [
      {
        title: 'PayPal',
        image: images.payPalIcon,
      },
      {
        title: 'Google Pay',
        image: images.googleIcon,
      },
      {
        title: 'Apple Pay',
        image: images.appleIcon,
      },
    ],
  },
  {
    title: 'Or Use a Bank Account',
    data: [
      {
        title: 'Bank of America',
        image: images.americaBankIcon,
        desc: true,
      },
      {
        title: 'JPMorgan Chase Bank',
        image: images.jpMorgonBankIcon,
        desc: true,
      },
      {
        title: 'Citibank',
        image: images.citiBankIcon,
        desc: true,
      },
      {
        title: 'Wells Fargo Bank',
        image: images.wellesForgoBankIcon,
        desc: true,
      },
    ],
  },
];

const WithdrawalOtradeData = [
  {
    title: 'Your Bank Account',
    data: [
      {
        desc: 'Bank of America',
        image: images.americaBankIcon,
        title: 'Andrew Ainsley',
      },
      {
        desc: 'JPMorgan Chase Bank',
        image: images.jpMorgonBankIcon,
        title: 'Andrew Ainsley',
      },
      {
        desc: 'Citibank',
        image: images.citiBankIcon,
        title: 'Andrew Ainsley',
      },
      {
        desc: 'Wells Fargo Bank',
        image: images.wellesForgoBankIcon,
        title: 'Andrew Ainsley',
      },
    ],
  },
  {
    title: 'Or Use a Connected Payment Methods',
    data: [
      {
        title: 'PayPal',
        image: images.payPalIcon,
      },
      {
        title: 'Google Pay',
        image: images.googleIcon,
      },
      {
        title: 'Apple Pay',
        image: images.appleIcon,
      },
    ],
  },
];

const addBankAccountData = [
  {
    title: 'Bank of America',
    image: images.americaBankIcon,
  },
  {
    title: 'JPMorgan Chase Bank',
    image: images.jpMorgonBankIcon,
  },
  {
    title: 'Ally Financial',
    image: images.allyBankIcon,
  },
  {
    title: 'Capital One',
    image: images.capitalOneBankIcon,
  },
  {
    title: 'Citibank',
    image: images.citiBankIcon,
  },
  {
    title: 'Toronto Dominion Bank',
    image: images.torontoBankIcon,
  },
  {
    title: 'US Bancorp',
    image: images.usBancorpBankIcon,
  },
];

const accountTypeData = [
  { label: 'Saving', value: 'Saving' },
  { label: 'Current', value: 'Current' },
  { label: 'Individual', value: 'Individual' },
  { label: 'Joint', value: 'Joint' },
  { label: 'Custodial', value: 'Custodial' },
  { label: 'Retirement', value: 'Retirement' },
  { label: 'Trust', value: 'Trust' },
  { label: 'Business', value: 'Business' },
  { label: 'Other', value: 'Other' },
];

const fundingActivityData = [
  {
    bank: images.americaBankIcon,
    desc: 'Deposit via Bank of America',
    amount: '+ $20,000',
    date: 'Dec 24, 2022',
    status: strings.successful,
  },
  {
    bank: images.jpMorgonBankIcon,
    desc: 'Withdrawal via JPMorgan Chase Bank',
    amount: '$15,000.00',
    date: 'Dec 15, 2022',
    status: strings.successful,
  },
  {
    bank: images.capitalOneBankIcon,
    desc: 'Deposit via Capital One',
    amount: '$10,000.00',
    date: 'Nov 30, 2022',
    status: strings.expired,
  },
  {
    bank: images.torontoBankIcon,
    desc: 'Deposit via Toronto Dominion Bank',
    amount: '$25,000.00',
    date: 'Nov 14, 2022',
    status: strings.successful,
  },
];

const financialTransactionData = [
  {
    id: 1,
    title: 'SPOT: Buy in Dollars',
    date: 'Dec 24, 2022',
    amount: '$10,000.00',
    value: '0.013659756',
    image: images.spotifyIcon,
    transactionType: 'stock_purchase',
    type: 'buy'
  },
  {
    id: 2,
    title: 'SPOT: Sell in Dollars',
    date: 'Dec 24, 2022',
    amount: '$5,000.00',
    value: '0.026487494',
    image: images.spotifyIcon,
    transactionType: 'stock_sale',
    type: 'sell'
  },
  {
    id: 3,
    title: 'TSLA: Exchange in Dollars',
    date: 'Dec 24, 2022',
    amount: '$10,000.00',
    value: '0.017365862',
    image: images.teslaIcon,
    transactionType: 'stock_exchange',
    type: 'exchange'
  },
  {
    id: 4,
    title: 'AAPL: Buy in Dollars',
    date: 'Dec 24, 2022',
    amount: '$25,000.00',
    value: '0.025573978',
    image: images.appleIcon,
    transactionType: 'stock_purchase',
    type: 'buy'
  },
  {
    id: 5,
    title: 'PINS: Sell in Dollars',
    date: 'Dec 20, 2022',
    amount: '$8,000.00',
    value: '0.014236557',
    image: images.googleIcon,
    transactionType: 'stock_sale',
    type: 'sell'
  },
  {
    id: 6,
    title: 'GOOGL: Exchange in Dollars',
    date: 'Dec 02, 2022',
    amount: '$15,000.00',
    value: '0.012576639',
    image: images.googleIcon,
    transactionType: 'stock_exchange',
    type: 'exchange'
  },
  {
    id: 7,
    title: 'META: Sell in Dollars',
    date: 'Sep 13, 2022',
    amount: '$10,000.00',
    value: '0.012874537',
    image: images.metaIcon,
    transactionType: 'stock_sale',
    type: 'sell'
  },
  // Transfer transactions
  {
    id: 1001,
    title: 'BTC: Sent to Wallet',
    date: 'Dec 23, 2022',
    amount: '$1,250.50',
    value: '0.058234000',
    image: images.bitcoinIcon,
    transactionType: 'asset_transfer',
    type: 'sent',
    recipientAddress: '1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa',
    transactionHash: '0xab1cd2ef3456789012345678901234567890123456789012345678901234567890',
    fees: 2.50,
    status: 'completed'
  },
  {
    id: 1002,
    title: 'ETH: Received from Wallet',
    date: 'Dec 22, 2022',
    amount: '$800.00',
    value: '0.634567000',
    image: images.ethereumIcon,
    transactionType: 'asset_transfer',
    type: 'received',
    senderAddress: '0x742d35Cc6634C0532925a3b8D6a8b8F8eF7326AB',
    transactionHash: '0xcd2ef3456789012345678901234567890123456789012345678901234567890ab',
    fees: 1.25,
    status: 'completed'
  },
  {
    id: 1003,
    title: 'USDT: Sent to Exchange',
    date: 'Dec 21, 2022',
    amount: '$500.00',
    value: '500.000000000',
    image: images.usdtIcon,
    transactionType: 'asset_transfer',
    type: 'sent',
    recipientAddress: '0x8ba1f109551bD432803012645Hac136c6a67890e',
    transactionHash: '0xef3456789012345678901234567890123456789012345678901234567890abcd',
    fees: 1.00,
    status: 'completed'
  },
  {
    id: 1004,
    title: 'SOL: Received from DeFi',
    date: 'Dec 20, 2022',
    amount: '$320.75',
    value: '15.250000000',
    image: images.solanaIcon,
    transactionType: 'asset_transfer',
    type: 'received',
    senderAddress: 'DRiP2Pn2K6fuMLKQmt5rZWxa4dkHUSaKUKU',
    transactionHash: '0x456789012345678901234567890123456789012345678901234567890abcdef',
    fees: 0.50,
    status: 'completed'
  },
];

const paymentMethodsData = [
  {
    title: 'PayPal',
    image: images.payPalIcon,
  },
  {
    title: 'Google Pay',
    image: images.googleIcon,
  },
  {
    title: 'Apple Pay',
    image: images.appleIcon,
  },
  {
    title: '•••• •••• •••• •••• 4679',
    image: images.masterIcon,
  },
  {
    title: '•••• •••• •••• •••• 5874',
    image: images.visaIcon,
  },
  {
    title: '•••• •••• •••• •••• 7958',
    image: images.masterIcon,
  },
  {
    title: '•••• •••• •••• •••• 1348',
    image: images.amreicanExpressIcon,
  },
  {
    title: '•••• •••• •••• •••• 1789',
    image: images.masterIcon,
  },
  {
    title: '•••• •••• •••• •••• 6832',
    image: images.visaIcon,
  },
  {
    title: '•••• •••• •••• •••• 5732',
    image: images.amreicanExpressIcon,
  },
];

const stockCategoryData = [
  '✅ All Stocks',
  '🚀 Visionary',
  '🔥 Hot Stocks',
  '💎 Blue Chips',
  '📈 Growth',
  '🛒 Retail',
  '🏥 Healthcare',
  '🏭 Industrial',
  '⚡ Energy',
  '🏬 Real Estate',
  '📦 Logistics',
  '🧠 Tech',
  '🏦 Fintech',
  '🔁 Blockchain',
  '📊 ETF',
  '💎 Commodities',
];

const topMoversData = [
  {
    image: images.pinterestIcon,
    companyName: 'Pinterest',
    stockName: 'PINS',
    currentValue: '$25.75',
    percentage: '12.37%',
    data: [
      { x: -2, y: 15 },
      { x: -1, y: 10 },
      { x: 0, y: 12 },
      { x: 1, y: 7 },
      { x: 2, y: 6 },
      { x: 3, y: 8 },
      { x: 4, y: 10 },
      { x: 5, y: 8 },
      { x: 6, y: 12 },
      { x: 7, y: 14 },
      { x: 8, y: 12 },
      { x: 9, y: 13.5 },
      { x: 10, y: 18 },
    ],
    status: true,
  },
  {
    image: images.slackIcon,
    companyName: 'Slack',
    stockName: 'WORK',
    currentValue: '$12.5',
    percentage: '9.37%',
    data: [
      { x: -2, y: 15 },
      { x: -1, y: 10 },
      { x: 0, y: 12 },
      { x: 1, y: 7 },
      { x: 2, y: 6 },
      { x: 3, y: 8 },
      { x: 4, y: 10 },
      { x: 5, y: 8 },
      { x: 6, y: 12 },
      { x: 7, y: 14 },
      { x: 8, y: 12 },
      { x: 9, y: 13.5 },
      { x: 10, y: 18 },
    ],
    status: true,
  },
  {
    image: images.hpIcon,
    companyName: 'HP Inc.',
    stockName: 'HPQ',
    currentValue: '$12.5',
    percentage: '6.7%',
    data: [
      { x: -2, y: 15 },
      { x: -1, y: 10 },
      { x: 0, y: 12 },
      { x: 1, y: 7 },
      { x: 2, y: 6 },
      { x: 3, y: 8 },
      { x: 4, y: 10 },
      { x: 5, y: 13.8 },
      { x: 6, y: 15.4 },
      { x: 7, y: 3.1 },
      { x: 8, y: 12.9 },
      { x: 9, y: 19.7 },
      { x: 10, y: 11.5 },
    ],
    status: true,
  },
  {
    image: images.linkedinIcon,
    companyName: 'LinkedIn Corporation',
    stockName: 'LNKD',
    currentValue: '$142.5',
    percentage: '7.37%',
    data: [
      { x: -2, y: 10.2 },
      { x: -1, y: 17.5 },
      { x: 0, y: 16.8 },
      { x: 1, y: 18.1 },
      { x: 2, y: 15.3 },
      { x: 3, y: 14.7 },
      { x: 4, y: 7.2 },
      { x: 5, y: 13.8 },
      { x: 6, y: 15.4 },
      { x: 7, y: 3.1 },
      { x: 8, y: 12.9 },
      { x: 9, y: 19.7 },
      { x: 10, y: 11.5 },
    ],
    status: true,
  },
  {
    image: images.mozilaIcon,
    companyName: 'Mozila Corporation',
    stockName: 'MOZ',
    currentValue: '$65.3',
    percentage: '6.37%',
    data: [
      { x: -2, y: 15 },
      { x: -1, y: 10 },
      { x: 0, y: 12 },
      { x: 1, y: 7 },
      { x: 2, y: 6 },
      { x: 3, y: 12.9 },
      { x: 4, y: 3.6 },
      { x: 5, y: 14.2 },
      { x: 6, y: 13.8 },
      { x: 7, y: 14.7 },
      { x: 8, y: 10.1 },
      { x: 9, y: 14.6 },
      { x: 10, y: 20 },
    ],
    status: true,
  },
  {
    image: images.burgerKingIcon,
    companyName: 'Burger King',
    stockName: 'BKG',
    currentValue: '$54.3',
    percentage: '5.37%',
    data: [
      { x: -2, y: 6.3 },
      { x: -1, y: 11.8 },
      { x: 0, y: 13.2 },
      { x: 1, y: 12.1 },
      { x: 2, y: 11.5 },
      { x: 3, y: 12.9 },
      { x: 4, y: 3.6 },
      { x: 5, y: 14.2 },
      { x: 6, y: 13.8 },
      { x: 7, y: 14.7 },
      { x: 8, y: 10.1 },
      { x: 9, y: 14.6 },
      { x: 10, y: 20 },
    ],
    status: true,
  },
];

const discoverStockData = [
  {
    image: images.discoverImage11,
    title: '🔥 10 Most Popular Stocks',
    desc: 'Follow the crowd',
  },
  {
    image: images.discoverImage10,
    title: '📺 Social Media',
    desc: 'Know each other',
  },
  {
    image: images.discoverImage3,
    title: '🏦 Financials',
    desc: 'Manage your finance',
  },
  {
    image: images.discoverImage7,
    title: '🛍 E-Commerce',
    desc: 'Get your favorite item',
  },
  {
    image: images.discoverImage4,
    title: '💻 Cryptocurrency',
    desc: 'Invest in cryptocurrency',
  },
  {
    image: images.discoverImage8,
    title: '🌲 Green Energy',
    desc: 'Renewable energy',
  },
  {
    image: images.discoverImage2,
    title: '🏥 Healthcare',
    desc: 'Health and mental issues',
  },
  {
    image: images.discoverImage5,
    title: '🏘 Real Estate',
    desc: 'Your dream home is here',
  },
  {
    image: images.discoverImage9,
    title: '😎 Lifestyle Brands',
    desc: 'Enjoy life together',
  },
  {
    image: images.discoverImage6,
    title: '🎨 Design Brands',
    desc: 'Improve creative workflow',
  },
];

const discoverListedStock = [
  {
    id: 1,
    image: images.adobeIcon,
    companyName: 'Adobe',
    stockName: 'ADBE',
    currentValue: '$285.75',
    percentage: '4.58%',
    data: [
      { x: -2, y: 15 },
      { x: -1, y: 10 },
      { x: 0, y: 12 },
      { x: 1, y: 7 },
      { x: 2, y: 6 },
      { x: 3, y: 8 },
      { x: 4, y: 10 },
      { x: 5, y: 8 },
      { x: 6, y: 12 },
      { x: 7, y: 14 },
      { x: 8, y: 12 },
      { x: 9, y: 13.5 },
      { x: 10, y: 18 },
    ],
    status: false,
  },
  {
    id: 2,
    image: images.amdIcon,
    companyName: 'Advanced Micro Devices',
    stockName: 'AMD',
    currentValue: '$68.26',
    percentage: '3.58%',
    data: [
      { x: -2, y: 10 },
      { x: -1, y: 12 },
      { x: 0, y: 8 },
      { x: 1, y: 6 },
      { x: 2, y: 7 },
      { x: 3, y: 9 },
      { x: 4, y: 11 },
      { x: 5, y: 9 },
      { x: 6, y: 13 },
      { x: 7, y: 15 },
      { x: 8, y: 13 },
      { x: 9, y: 14.5 },
      { x: 10, y: 19 },
    ],
    status: true,
  },
  {
    id: 3,
    image: images.adobeIcon,
    companyName: 'Airbnb',
    stockName: 'ABNB',
    currentValue: '$150.00',
    percentage: '4.23%',
    status: true,
    data: [
      { x: -2, y: 10 },
      { x: -1, y: 12 },
      { x: 0, y: 3 },
      { x: 1, y: 16 },
      { x: 2, y: 3 },
      { x: 3, y: 9 },
      { x: 4, y: 1 },
      { x: 5, y: 9 },
      { x: 6, y: 10 },
      { x: 7, y: 5 },
      { x: 8, y: 13 },
      { x: 9, y: 1.5 },
      { x: 10, y: 10 },
    ],
  },
  {
    id: 4,
    image: images.alibabaIcon,
    companyName: 'Alibaba',
    stockName: 'BABA',
    currentValue: '$89.24',
    percentage: '5.28%',
    status: false,
    data: [
      { x: -2, y: 4 },
      { x: -1, y: 2 },
      { x: 0, y: 7 },
      { x: 1, y: 6 },
      { x: 2, y: 13 },
      { x: 3, y: 3 },
      { x: 4, y: 9 },
      { x: 5, y: 10 },
      { x: 6, y: 10 },
      { x: 7, y: 5 },
      { x: 8, y: 1 },
      { x: 9, y: 1.5 },
      { x: 10, y: 17.4 },
    ],
  },
  {
    id: 5,
    image: images.amazonIcon,
    companyName: 'Amazon',
    stockName: 'AMZN',
    currentValue: '$90.96',
    percentage: '2.28%',
    status: true,
    data: [
      { x: -2, y: 8 },
      { x: -1, y: 3 },
      { x: 0, y: 6 },
      { x: 1, y: 9 },
      { x: 2, y: 12 },
      { x: 3, y: 5 },
      { x: 4, y: 11 },
      { x: 5, y: 14 },
      { x: 6, y: 7 },
      { x: 7, y: 2 },
      { x: 8, y: 4 },
      { x: 9, y: 10 },
      { x: 10, y: 5.8 },
    ],
  },
  {
    id: 6,
    image: images.appleIcon,
    companyName: 'Apple',
    stockName: 'AAPL',
    currentValue: '$120.00',
    percentage: '2.45%',
    status: true,
    data: [
      { x: -2, y: 4 },
      { x: -1, y: 2 },
      { x: 0, y: 7 },
      { x: 1, y: 16 },
      { x: 2, y: 13 },
      { x: 3, y: 13 },
      { x: 4, y: 19 },
      { x: 5, y: 10 },
      { x: 6, y: 10 },
      { x: 7, y: 5 },
      { x: 8, y: 1 },
      { x: 9, y: 1.5 },
      { x: 10, y: 7.4 },
    ],
  },
  {
    id: 7,
    image: images.citiBankIcon,
    companyName: 'Citibank',
    stockName: 'C',
    currentValue: '$58.98',
    percentage: '1.28%',
    status: false,
    data: [
      { x: -2, y: 1 },
      { x: -1, y: 15 },
      { x: 0, y: 10 },
      { x: 1, y: 19 },
      { x: 2, y: 15 },
      { x: 3, y: 16 },
      { x: 4, y: 2 },
      { x: 5, y: 1 },
      { x: 6, y: 3 },
      { x: 7, y: 13 },
      { x: 8, y: 2 },
      { x: 9, y: 2.5 },
      { x: 10, y: 20.1 },
    ],
  },
  {
    id: 8,
    image: images.cocoColaIcon,
    companyName: 'Coco Cola',
    stockName: 'KO',
    currentValue: '$64.56',
    percentage: '2.61%',
    status: true,
    data: [
      { x: -2, y: 8 },
      { x: -1, y: 3 },
      { x: 0, y: 6 },
      { x: 1, y: 9 },
      { x: 2, y: 12 },
      { x: 3, y: 4 },
      { x: 4, y: 8 },
      { x: 5, y: 11 },
      { x: 6, y: 7 },
      { x: 7, y: 3 },
      { x: 8, y: 2 },
      { x: 9, y: 5 },
      { x: 10, y: 15 },
    ],
  },
];

const topStockData = [
  {
    id: 1,
    stockName: 'DOW',
    currentValue: '$285.75',
    percentage: '3.58%',
    image: images.niftyImg,
    data: [
      { x: -2, y: 15 },
      { x: -1, y: 11 },
      { x: 0, y: 2 },
      { x: 1, y: 7 },
      { x: 2, y: 6 },
      { x: 3, y: 8 },
      { x: 4, y: 10 },
      { x: 5, y: 18 },
      { x: 6, y: 10 },
      { x: 7, y: 20 },
      { x: 8, y: 8 },
      { x: 9, y: 13.5 },
      { x: 10, y: 22 },
    ],
    status: true,
  },
  {
    id: 2,
    stockName: 'S&P 500',
    image: images.niftyImg,
    percentage: '1.96%',
    data: [
      { x: -2, y: 15 },
      { x: -1, y: 12 },
      { x: 0, y: 18 },
      { x: 1, y: 16 },
      { x: 2, y: 17 },
      { x: 3, y: 19 },
      { x: 4, y: 11 },
      { x: 5, y: 19 },
      { x: 6, y: 5 },
      { x: 7, y: 9 },
      { x: 8, y: 13 },
      { x: 9, y: 14.5 },
      { x: 10, y: 8 },
    ],
    status: false,
  },
  {
    id: 3,
    stockName: 'NASDAQ',
    image: images.niftyImg,
    percentage: '2.85%',
    status: true,
    data: [
      { x: -2, y: 0 },
      { x: -1, y: 12 },
      { x: 0, y: 13 },
      { x: 1, y: 16 },
      { x: 2, y: 13 },
      { x: 3, y: 19 },
      { x: 4, y: 11 },
      { x: 5, y: 9 },
      { x: 6, y: 5 },
      { x: 7, y: 5 },
      { x: 8, y: 3 },
      { x: 9, y: 1.5 },
      { x: 10, y: 20 },
    ],
  },
];

const myWishlistStockData = [
  {
    id: 5,
    image: images.twitterIcon,
    companyName: 'Twitter',
    stockName: 'TWTR',
    currentValue: '$56.96',
    percentage: '3.26%',
    status: true,
    data: [
      { x: -2, y: 18 },
      { x: -1, y: 13 },
      { x: 0, y: 16 },
      { x: 1, y: 19 },
      { x: 2, y: 8 },
      { x: 3, y: 5 },
      { x: 4, y: 13 },
      { x: 5, y: 14 },
      { x: 6, y: 17 },
      { x: 7, y: 12 },
      { x: 8, y: 17 },
      { x: 9, y: 10 },
      { x: 10, y: 15.8 },
    ],
  },
  {
    id: 5,
    image: images.amazonIcon,
    companyName: 'Amazon',
    stockName: 'AMZN',
    currentValue: '$90.96',
    percentage: '2.28%',
    status: false,
    data: [
      { x: -2, y: 8 },
      { x: -1, y: 3 },
      { x: 0, y: 6 },
      { x: 1, y: 9 },
      { x: 2, y: 12 },
      { x: 3, y: 5 },
      { x: 4, y: 11 },
      { x: 5, y: 14 },
      { x: 6, y: 7 },
      { x: 7, y: 2 },
      { x: 8, y: 4 },
      { x: 9, y: 10 },
      { x: 10, y: 5.8 },
    ],
  },
  {
    id: 5,
    image: images.teslaIcon,
    companyName: 'Tesla',
    stockName: 'TSLA',
    currentValue: '$65.89',
    percentage: '1.34%',
    status: true,
    data: [
      { x: -2, y: 12 },
      { x: -1, y: 15 },
      { x: 0, y: 18 },
      { x: 1, y: 14 },
      { x: 2, y: 13.5 },
      { x: 3, y: 11 },
      { x: 4, y: 16.8 },
      { x: 5, y: 10.5 },
      { x: 6, y: 17 },
      { x: 7, y: 12.7 },
      { x: 8, y: 19.2 },
      { x: 9, y: 11.8 },
      { x: 10, y: 15.9 },
    ],
  },
  {
    id: 5,
    image: images.cocoColaIcon,
    companyName: 'Coco Cola',
    stockName: 'KO',
    currentValue: '$42.56',
    percentage: '4.61%',
    status: false,
    data: [
      { x: -2, y: 15.2 },
      { x: -1, y: 12.8 },
      { x: 0, y: 17.9 },
      { x: 1, y: 14.7 },
      { x: 2, y: 18.6 },
      { x: 3, y: 11.3 },
      { x: 4, y: 16.9 },
      { x: 5, y: 14.5 },
      { x: 6, y: 15.1 },
      { x: 7, y: 12.5 },
      { x: 8, y: 10.2 },
      { x: 9, y: 11.8 },
      { x: 10, y: 19.3 },
    ],
  },
];

const myStockData = [
  {
    id: 1,
    image: images.amazonIcon,
    companyName: 'Amazon',
    stockName: 'AMZN',
    currentValue: '$3,200.45',
    percentage: '2.34%',
    data: [
      { x: -2, y: 12 },
      { x: -1, y: 11 },
      { x: 0, y: 15 },
      { x: 1, y: 18 },
      { x: 2, y: 14 },
      { x: 3, y: 13 },
      { x: 4, y: 12 },
      { x: 5, y: 11 },
      { x: 6, y: 10 },
      { x: 7, y: 10 },
      { x: 8, y: 11 },
      { x: 9, y: 13 },
      { x: 10, y: 17 },
    ],
    status: false,
    staking: {
      staked: '$125.78',
      unstaked: '$54.20',
      apy: '12.5%',
      availableBalance: '$1,250.00',
      lockPeriod: '30 days',
      minStakeAmount: '$10.00',
      maxStakeAmount: '$10,000.00',
      stakingFees: '$2.50',
    },
  },
  {
    id: 2,
    image: images.spotifyIcon,
    companyName: 'Spotify',
    stockName: 'SPOT',
    currentValue: '$165.45',
    percentage: '2.55%',
    data: [
      { x: -2, y: 11 },
      { x: -1, y: 13 },
      { x: 0, y: 15 },
      { x: 1, y: 14 },
      { x: 2, y: 16 },
      { x: 3, y: 19 },
      { x: 4, y: 18 },
      { x: 5, y: 16 },
      { x: 6, y: 17 },
      { x: 7, y: 14 },
      { x: 8, y: 13 },
      { x: 9, y: 12.5 },
      { x: 10, y: 19.5 },
    ],
    status: false,
    staking: {
      staked: '$89.32',
      unstaked: '$76.13',
      apy: '8.7%',
      availableBalance: '$850.00',
      lockPeriod: '14 days',
      minStakeAmount: '$5.00',
      maxStakeAmount: '$5,000.00',
      stakingFees: '$1.75',
    },
  },
  {
    id: 3,
    image: images.metaIcon,
    companyName: 'Meta',
    stockName: 'META',
    currentValue: '$150.25',
    percentage: '2.75%',
    data: [
      { x: -2, y: 11 },
      { x: -1, y: 12 },
      { x: 0, y: 10 },
      { x: 1, y: 9 },
      { x: 2, y: 11 },
      { x: 3, y: 12 },
      { x: 4, y: 10 },
      { x: 5, y: 11 },
      { x: 6, y: 10 },
      { x: 7, y: 9 },
      { x: 8, y: 8 },
      { x: 9, y: 10.5 },
      { x: 10, y: 12.8 },
    ],
    status: true,
    staking: {
      staked: '$0',
      unstaked: '$150.25',
      apy: '15.2%',
      availableBalance: '$2,500.00',
      lockPeriod: '7 days',
      minStakeAmount: '$25.00',
      maxStakeAmount: '$15,000.00',
      stakingFees: '$3.00',
    },
  },
  {
    id: 4,
    image: images.googleIcon,
    companyName: 'Alphabet Inc.',
    stockName: 'GOOGL',
    currentValue: '$2855.75',
    percentage: '4.58%',
    data: [
      { x: -2, y: 14.5 },
      { x: -1, y: 10.2 },
      { x: 0, y: 11.8 },
      { x: 1, y: 8.7 },
      { x: 2, y: 7.4 },
      { x: 3, y: 9.2 },
      { x: 4, y: 10.5 },
      { x: 5, y: 8.9 },
      { x: 6, y: 11.3 },
      { x: 7, y: 13.8 },
      { x: 8, y: 11.7 },
      { x: 9, y: 12.9 },
      { x: 10, y: 17.7 },
    ],
    status: true,
    staking: {
      staked: '$0',
      unstaked: '$150.25',
    },
  },
  {
    id: 5,
    image: images.macdonaldsIcon,
    companyName: "McDonald's Corporation",
    stockName: 'MCD',
    currentValue: '$235.40',
    percentage: '2.11%',
    data: [
      { x: -2, y: 19.8 },
      { x: -1, y: 6.5 },
      { x: 0, y: 12.0 },
      { x: 1, y: 13.3 },
      { x: 2, y: 10.9 },
      { x: 3, y: 10.5 },
      { x: 4, y: 1.2 },
      { x: 5, y: 13.0 },
      { x: 6, y: 10.7 },
      { x: 7, y: 10.2 },
      { x: 8, y: 10.5 },
      { x: 9, y: 10.8 },
      { x: 10, y: 11.4 },
    ],
    status: false,
  },
  {
    id: 6,
    image: images.netflixIcon,
    companyName: 'Netflix, Inc.',
    stockName: 'NFLX',
    currentValue: '$520.45',
    percentage: '2.14%',
    data: [
      { x: -2, y: 10.2 },
      { x: -1, y: 17.5 },
      { x: 0, y: 16.8 },
      { x: 1, y: 18.1 },
      { x: 2, y: 15.3 },
      { x: 3, y: 14.7 },
      { x: 4, y: 7.2 },
      { x: 5, y: 13.8 },
      { x: 6, y: 15.4 },
      { x: 7, y: 3.1 },
      { x: 8, y: 12.9 },
      { x: 9, y: 19.7 },
      { x: 10, y: 11.5 },
    ],
    status: false,
    staking: {
      staked: '$0',
      unstaked: '$150.25',
    },
  },
  {
    id: 2,
    image: images.cocoColaIcon,
    companyName: 'The Coca-Cola Company',
    stockName: 'KO',
    currentValue: '$52.35',
    percentage: '1.24%',
    data: [
      { x: -2, y: 18.8 },
      { x: -1, y: 3.5 },
      { x: 0, y: 11.3 },
      { x: 1, y: 7.7 },
      { x: 2, y: 12.2 },
      { x: 3, y: 11.8 },
      { x: 4, y: 10.1 },
      { x: 5, y: 11.5 },
      { x: 6, y: 11.9 },
      { x: 7, y: 12.3 },
      { x: 8, y: 11.7 },
      { x: 9, y: 12.5 },
      { x: 10, y: 20 },
    ],
    status: true,
    staking: {
      staked: '$0',
      unstaked: '$150.25',
    },
  },
  {
    id: 7,
    image: images.nikeIcon,
    companyName: 'Nike Inc.',
    stockName: 'NKE',
    currentValue: '$145.32',
    percentage: '2.34%',
    data: [
      { x: -2, y: 6.3 },
      { x: -1, y: 11.8 },
      { x: 0, y: 13.2 },
      { x: 1, y: 12.1 },
      { x: 2, y: 11.5 },
      { x: 3, y: 12.9 },
      { x: 4, y: 3.6 },
      { x: 5, y: 14.2 },
      { x: 6, y: 13.8 },
      { x: 7, y: 14.7 },
      { x: 8, y: 10.1 },
      { x: 9, y: 14.6 },
      { x: 10, y: 20 },
    ],
    status: false,
    staking: {
      staked: '$0',
      unstaked: '$150.25',
    },
  },
  {
    id: 8,
    image: images.starbucksIcon,
    companyName: 'Starbucks Corporation',
    stockName: 'SBUX',
    currentValue: '$98.25',
    percentage: '2.15%',
    data: [
      { x: -2, y: 11.5 },
      { x: -1, y: 13.2 },
      { x: 0, y: 14.8 },
      { x: 1, y: 12.7 },
      { x: 2, y: 10.4 },
      { x: 3, y: 12.2 },
      { x: 4, y: 17.5 },
      { x: 5, y: 10.9 },
      { x: 6, y: 12.3 },
      { x: 7, y: 10.8 },
      { x: 8, y: 12.7 },
      { x: 9, y: 11.9 },
      { x: 10, y: 14.2 },
    ],
    status: true,
    staking: {
      staked: '$0',
      unstaked: '$150.25',
    },
  },
  {
    id: 8,
    image: images.airbnbIcon,
    companyName: 'Airbnb, Inc.',
    stockName: 'ABNB',
    currentValue: '$170.28',
    percentage: '1.18%',
    data: [
      { x: -2, y: 14.3 },
      { x: -1, y: 11.8 },
      { x: 0, y: 13.5 },
      { x: 1, y: 9.7 },
      { x: 2, y: 8.2 },
      { x: 3, y: 10.4 },
      { x: 4, y: 12.1 },
      { x: 5, y: 10.8 },
      { x: 6, y: 13.2 },
      { x: 7, y: 14.9 },
      { x: 8, y: 13.7 },
      { x: 9, y: 14.3 },
      { x: 10, y: 19.1 },
    ],
    status: false,
    staking: {
      staked: '$89.32',
      unstaked: '$76.13',
    },
  },
];

const stockTimeData = ['1D', '1W', '1M', '3M', '6M', '1Y', '5Y'];

const spotMarketStats = [
  {
    id: 1,
    title: 'Market Cap',
    value: '$2.5T',
    icon: <MarketCapIcon />,
  },
  {
    id: 2,
    title: 'Price-Earnings Ratio',
    value: 'N/A',
    icon: <PriceEarningsRatioIcon />,
  },
  {
    id: 3,
    title: 'Dividend Yield',
    value: 'N/A',
    icon: <DividendYieldIcon />,
  },
  {
    id: 4,
    title: 'Average Volume',
    value: 'N/A',
    icon: <AvgVolumeIcon />,
  },
  {
    id: 4,
    title: 'Earnings Per Share',
    value: 'N/A',
    icon: <BuySharesIcon />,
  },
  {
    id: 5,
    title: '52 Week High',
    value: '$3,773.08',
    icon: <HighIcon />,
  },
  {
    id: 6,
    title: '52 Week Low',
    value: '$2,871.00',
    icon: <LowIcon />,
  },
];

const characteristicsData = [
  '✅ All Stocks',
  '🚀 Visionary',
  '💪 Founder-Led',
  '😎 Lifestyle',
  '🎇 Entertainment',
  '💻 Tech',
];

const similarStocksData = [
  {
    image: images.pinterestIcon,
    companyName: 'Pinterest',
    stockName: 'PINS',
    currentValue: '$25.75',
    percentage: '12.37%',
    data: [
      { x: -2, y: 15 },
      { x: -1, y: 10 },
      { x: 0, y: 12 },
      { x: 1, y: 7 },
      { x: 2, y: 6 },
      { x: 3, y: 8 },
      { x: 4, y: 10 },
      { x: 5, y: 8 },
      { x: 6, y: 12 },
      { x: 7, y: 14 },
      { x: 8, y: 12 },
      { x: 9, y: 13.5 },
      { x: 10, y: 18 },
    ],
    status: false,
  },
  {
    image: images.slackIcon,
    companyName: 'Slack',
    stockName: 'WORK',
    currentValue: '$12.5',
    percentage: '9.37%',
    data: [
      { x: -2, y: 15 },
      { x: -1, y: 10 },
      { x: 0, y: 12 },
      { x: 1, y: 7 },
      { x: 2, y: 6 },
      { x: 3, y: 8 },
      { x: 4, y: 10 },
      { x: 5, y: 8 },
      { x: 6, y: 12 },
      { x: 7, y: 14 },
      { x: 8, y: 12 },
      { x: 9, y: 13.5 },
      { x: 10, y: 18 },
    ],
    status: true,
  },
  {
    image: images.hpIcon,
    companyName: 'HP Inc.',
    stockName: 'HPQ',
    currentValue: '$12.5',
    percentage: '6.7%',
    data: [
      { x: -2, y: 15 },
      { x: -1, y: 10 },
      { x: 0, y: 12 },
      { x: 1, y: 7 },
      { x: 2, y: 6 },
      { x: 3, y: 8 },
      { x: 4, y: 10 },
      { x: 5, y: 13.8 },
      { x: 6, y: 15.4 },
      { x: 7, y: 3.1 },
      { x: 8, y: 12.9 },
      { x: 9, y: 19.7 },
      { x: 10, y: 11.5 },
    ],
    status: false,
  },
  {
    image: images.linkedinIcon,
    companyName: 'LinkedIn Corporation',
    stockName: 'LNKD',
    currentValue: '$142.5',
    percentage: '7.37%',
    data: [
      { x: -2, y: 10.2 },
      { x: -1, y: 17.5 },
      { x: 0, y: 16.8 },
      { x: 1, y: 18.1 },
      { x: 2, y: 15.3 },
      { x: 3, y: 14.7 },
      { x: 4, y: 7.2 },
      { x: 5, y: 13.8 },
      { x: 6, y: 15.4 },
      { x: 7, y: 3.1 },
      { x: 8, y: 12.9 },
      { x: 9, y: 19.7 },
      { x: 10, y: 11.5 },
    ],
    status: false,
  },
  {
    image: images.mozilaIcon,
    companyName: 'Mozila Corporation',
    stockName: 'MOZ',
    currentValue: '$65.3',
    percentage: '6.37%',
    data: [
      { x: -2, y: 15 },
      { x: -1, y: 10 },
      { x: 0, y: 12 },
      { x: 1, y: 7 },
      { x: 2, y: 6 },
      { x: 3, y: 12.9 },
      { x: 4, y: 3.6 },
      { x: 5, y: 14.2 },
      { x: 6, y: 13.8 },
      { x: 7, y: 14.7 },
      { x: 8, y: 10.1 },
      { x: 9, y: 14.6 },
      { x: 10, y: 20 },
    ],
    status: true,
  },
  {
    image: images.burgerKingIcon,
    companyName: 'Burger King',
    stockName: 'BKG',
    currentValue: '$54.3',
    percentage: '5.37%',
    data: [
      { x: -2, y: 6.3 },
      { x: -1, y: 11.8 },
      { x: 0, y: 13.2 },
      { x: 1, y: 12.1 },
      { x: 2, y: 11.5 },
      { x: 3, y: 12.9 },
      { x: 4, y: 3.6 },
      { x: 5, y: 14.2 },
      { x: 6, y: 13.8 },
      { x: 7, y: 14.7 },
      { x: 8, y: 10.1 },
      { x: 9, y: 14.6 },
      { x: 10, y: 20 },
    ],
    status: false,
  },
];


{/* A supprimer une fois tout les people also supp */ }
const peopleAlsoBoughtData = [
  {
    image: images.pinterestIcon,
    companyName: 'Pinterest',
    stockName: 'PINS',
    currentValue: '$25.75',
    percentage: '12.37%',
    data: [
      { x: -2, y: 15 },
      { x: -1, y: 10 },
      { x: 0, y: 12 },
      { x: 1, y: 7 },
      { x: 2, y: 6 },
      { x: 3, y: 8 },
      { x: 4, y: 10 },
      { x: 5, y: 8 },
      { x: 6, y: 12 },
      { x: 7, y: 14 },
      { x: 8, y: 12 },
      { x: 9, y: 13.5 },
      { x: 10, y: 18 },
    ],
    status: false,
  },
  {
    image: images.slackIcon,
    companyName: 'Slack',
    stockName: 'WORK',
    currentValue: '$12.5',
    percentage: '9.37%',
    data: [
      { x: -2, y: 15 },
      { x: -1, y: 10 },
      { x: 0, y: 12 },
      { x: 1, y: 7 },
      { x: 2, y: 6 },
      { x: 3, y: 8 },
      { x: 4, y: 10 },
      { x: 5, y: 8 },
      { x: 6, y: 12 },
      { x: 7, y: 14 },
      { x: 8, y: 12 },
      { x: 9, y: 13.5 },
      { x: 10, y: 18 },
    ],
    status: true,
  },
  {
    image: images.hpIcon,
    companyName: 'HP Inc.',
    stockName: 'HPQ',
    currentValue: '$12.5',
    percentage: '6.7%',
    data: [
      { x: -2, y: 15 },
      { x: -1, y: 10 },
      { x: 0, y: 12 },
      { x: 1, y: 7 },
      { x: 2, y: 6 },
      { x: 3, y: 8 },
      { x: 4, y: 10 },
      { x: 5, y: 13.8 },
      { x: 6, y: 15.4 },
      { x: 7, y: 3.1 },
      { x: 8, y: 12.9 },
      { x: 9, y: 19.7 },
      { x: 10, y: 11.5 },
    ],
    status: false,
  },
  {
    image: images.linkedinIcon,
    companyName: 'LinkedIn Corporation',
    stockName: 'LNKD',
    currentValue: '$142.5',
    percentage: '7.37%',
    data: [
      { x: -2, y: 10.2 },
      { x: -1, y: 17.5 },
      { x: 0, y: 16.8 },
      { x: 1, y: 18.1 },
      { x: 2, y: 15.3 },
      { x: 3, y: 14.7 },
      { x: 4, y: 7.2 },
      { x: 5, y: 13.8 },
      { x: 6, y: 15.4 },
      { x: 7, y: 3.1 },
      { x: 8, y: 12.9 },
      { x: 9, y: 19.7 },
      { x: 10, y: 11.5 },
    ],
    status: false,
  },
  {
    image: images.mozilaIcon,
    companyName: 'Mozila Corporation',
    stockName: 'MOZ',
    currentValue: '$65.3',
    percentage: '6.37%',
    data: [
      { x: -2, y: 15 },
      { x: -1, y: 10 },
      { x: 0, y: 12 },
      { x: 1, y: 7 },
      { x: 2, y: 6 },
      { x: 3, y: 12.9 },
      { x: 4, y: 3.6 },
      { x: 5, y: 14.2 },
      { x: 6, y: 13.8 },
      { x: 7, y: 14.7 },
      { x: 8, y: 10.1 },
      { x: 9, y: 14.6 },
      { x: 10, y: 20 },
    ],
    status: true,
  },
  {
    image: images.burgerKingIcon,
    companyName: 'Burger King',
    stockName: 'BKG',
    currentValue: '$54.3',
    percentage: '5.37%',
    data: [
      { x: -2, y: 6.3 },
      { x: -1, y: 11.8 },
      { x: 0, y: 13.2 },
      { x: 1, y: 12.1 },
      { x: 2, y: 11.5 },
      { x: 3, y: 12.9 },
      { x: 4, y: 3.6 },
      { x: 5, y: 14.2 },
      { x: 6, y: 13.8 },
      { x: 7, y: 14.7 },
      { x: 8, y: 10.1 },
      { x: 9, y: 14.6 },
      { x: 10, y: 20 },
    ],
    status: false,
  },
];

const portfolioData = {
  id: 2,
  image: images.spotifyIcon,
  companyName: 'Spotify',
  stockName: 'SPOT',
  currentValue: '$196,548.50',
  percentage: '24.65%',
  data: [
    { x: -2, y: 11 },
    { x: -1, y: 13 },
    { x: 0, y: 15 },
    { x: 1, y: 14 },
    { x: 2, y: 16 },
    { x: 3, y: 19 },
    { x: 4, y: 18 },
    { x: 5, y: 16 },
    { x: 6, y: 17 },
    { x: 7, y: 14 },
    { x: 8, y: 13 },
    { x: 9, y: 12.5 },
    { x: 10, y: 19.5 },
  ],
  status: false,
};

const newsData = [
  {
    title: 'Forbes',
    desc: 'The Wall Street Journal: Apple, Microsoft, Alphabet, Facebook, Tesla, Boeing, and more stocks to watch this week',
    time: '1 days ago',
  },
  {
    title: 'Seeking Alpha',
    desc: 'Own The Toll Booths',
    time: '2 days ago',
  },
  {
    title: 'The Motley Fool',
    desc: 'Cathie Wood Has Abandoned Spotify --Should You Follow Her Lead?',
    time: '2 days ago',
  },
  {
    title: 'TipRanks',
    desc: 'Spotify Stock Dips as Investments in Growth Persist',
    time: '3 days ago',
  },
  {
    title: 'CNN Business',
    desc: 'Spotify is going to war with Apple after the App Store rejected its big new feature',
    time: '3 days ago',
  },
  {
    title: 'NY Times',
    desc: "People Love to Hate-Watch Tech Villains. That Won't Hurt Spotify.",
    time: '4 days ago',
  },
  {
    title: 'JP Morgan',
    desc: '2 Reasons to Buy Spotify Stock Right Now',
    time: '5 days ago',
  },
];

const buySellCategory = [
  {
    title: 'Market Orders',
    data: [
      {
        desc: 'Buy in Dollars',
        image: <PriceEarningsRatioIcon height={commonWH} width={commonWH} />,
        title: 'Buy SPOT for a dollar value at a minimum of $1.',
      },
      {
        desc: 'Buy in Shares',
        image: <BuySharesIcon height={commonWH} width={commonWH} />,
        title: 'Buy SPOT at a minimum 0.000000001 shares.',
      },
    ],
  },
  {
    title: 'Conditional Orders',
    data: [
      {
        title: 'Buy SPOT at a maximum price or lower. Minimum 1 share',
        image: <AvgVolumeIcon height={commonWH} width={commonWH} />,
        desc: 'Limit Order',
      },
      {
        title: 'Buy SPOT if rises to a fixed stop price. Minimum 1 share',
        desc: 'Stop Order',
        image: <ExchangeStockIcon height={commonWH} width={commonWH} />,
      },
    ],
  },
];

const notificationData = [
  {
    id: 1,
    title: 'Security Updates!',
    desc: 'Now Invest has a Two-Factor Authentication. Try it now to make your account more secure.',
    time: 'Today | 09:24 AM',
    isNew: true,
    icon: <NotificationIcon6 />,
  },
  {
    id: 2,
    title: 'Multiple Card Features!',
    desc: 'Now you can also connect Invest with multiple MasterCard & Visa. Try the service now.',
    time: '1 day ago | 14:43 PM',
    isNew: true,
    icon: <NotificationIcon5 />,
  },
  {
    id: 3,
    title: 'New Update Available!',
    desc: 'Update Invest now to get access to the latest features for easier in buy or sell stocks. ',
    time: '2 day ago | 14:35 PM',
    isNew: false,
    icon: <NotificationIcon4 />,
  },
  {
    id: 4,
    title: 'Bank Account Connected!',
    desc: 'You have linked your account with a local bank. You can withdraw whenever you want.',
    time: '4 day ago | 17:24 PM',
    isNew: false,
    icon: <NotificationIcon3 />,
  },
  {
    id: 5,
    title: 'Credit Card Connected!',
    desc: 'Your credit card has been successfully linked with Invest. Enjoy our services.',
    time: '6 day ago | 15:38 AM',
    isNew: false,
    icon: <NotificationIcon2 />,
  },
  {
    id: 6,
    title: 'Account Setup Successful!',
    desc: 'Your account creation is successful, you can now experience our services.',
    time: '12 Dec, 2022 | 03:12 AM',
    isNew: false,
    icon: <NotificationIcon1 />,
  },
];

const mainChartData = [
  { x: 0, y: 19.35357448436584 },
  { x: 1, y: 6.863813673427186 },
  { x: 2, y: 17.276026376776407 },
  { x: 3, y: 0.7276499709238093 },
  { x: 4, y: 10.330372256410103 },
  { x: 5, y: 8.32942316191881 },
  { x: 6, y: 13.853776570478066 },
  { x: 7, y: 19.93626234651624 },
  { x: 8, y: 5.095352978132366 },
  { x: 9, y: 14.54348050100003 },
  { x: 10, y: 0.7324232279281029 },
  { x: 11, y: 4.250638980356478 },
  { x: 12, y: 9.462118845730444 },
  { x: 13, y: 18.874585646488164 },
  { x: 14, y: 0.9461631627522538 },
  { x: 15, y: 2.5746193137405093 },
  { x: 16, y: 18.975544645956926 },
  { x: 17, y: 3.5582672999194154 },
  { x: 18, y: 17.788728640007676 },
  { x: 19, y: 12.65200190185035 },
  { x: 20, y: 6.284710062295296 },
  { x: 21, y: 1.7500374777398053 },
  { x: 22, y: 8.319600488342257 },
  { x: 23, y: 5.630569428230996 },
  { x: 24, y: 10.182326748374983 },
  { x: 25, y: 2.8486503895809356 },
  { x: 26, y: 15.973098861957343 },
  { x: 27, y: 6.408270928354423 },
  { x: 28, y: 5.520423411024593 },
  { x: 29, y: 2.0147288415852116 },
  { x: 30, y: 9.005643576586879 },
  { x: 31, y: 16.777103692307154 },
  { x: 32, y: 16.424003876654353 },
  { x: 33, y: 10.838820247207755 },
  { x: 34, y: 4.031046582725746 },
  { x: 35, y: 8.526427386606182 },
  { x: 36, y: 14.224767957567018 },
  { x: 37, y: 19.129940843924672 },
  { x: 38, y: 13.65644317159839 },
  { x: 39, y: 18.483895308641905 },
  { x: 40, y: 10.145602392704001 },
  { x: 41, y: 19.585678756039027 },
  { x: 42, y: 13.786496776114863 },
  { x: 43, y: 8.31977461588513 },
  { x: 44, y: 7.256102544400271 },
  { x: 45, y: 19.22762055265537 },
  { x: 46, y: 5.313032920941703 },
  { x: 47, y: 6.557588180689919 },
  { x: 48, y: 11.434838606373205 },
  { x: 49, y: 11.672812733812972 },
  { x: 50, y: 4.799024889222947 },
  { x: 51, y: 3.0143046578152877 },
  { x: 52, y: 0.10973879823516386 },
  { x: 53, y: 16.854872469742322 },
  { x: 54, y: 17.53641089663434 },
  { x: 55, y: 7.3806029930656365 },
  { x: 56, y: 16.926419912311 },
  { x: 57, y: 3.5247659026402522 },
  { x: 58, y: 6.373853985702085 },
  { x: 59, y: 2.7475699049143265 },
  { x: 60, y: 1.8255695200676536 },
];

const sampleDataDates = [
  { x: '2016-01-02', open: 80, close: 40, high: 120, low: 10 },
  { x: '2016-01-03', open: 50, close: 80, high: 90, low: 20 },
  { x: '2016-01-04', open: 70, close: 22, high: 70, low: 5 },
  { x: '2016-01-05', open: 20, close: 35, high: 50, low: 10 },
  { x: '2016-01-06', open: 35, close: 30, high: 40, low: 3 },
  { x: '2016-01-07', open: 30, close: 90, high: 95, low: 30 },
  { x: '2016-01-08', open: 80, close: 81, high: 83, low: 75 },
  { x: '2016-01-09', open: 81, close: 85, high: 90, low: 80 },
  { x: '2016-01-10', open: 85, close: 90, high: 110, low: 50 },
  { x: '2016-01-11', open: 90, close: 110, high: 115, low: 90 },
  { x: '2016-01-12', open: 110, close: 130, high: 131, low: 110 },
  { x: '2016-01-13', open: 70, close: 80, high: 100, low: 60 },
  { x: '2016-01-14', open: 80, close: 90, high: 95, low: 80 },
  { x: '2016-01-15', open: 90, close: 100, high: 110, low: 90 },
  { x: '2016-01-16', open: 100, close: 120, high: 130, low: 100 },
  { x: '2016-01-17', open: 90, close: 90, high: 140, low: 70 },
  { x: '2016-01-18', open: 80, close: 100, high: 110, low: 80 },
  { x: '2016-01-19', open: 70, close: 110, high: 120, low: 50 },
  { x: '2016-01-20', open: 50, close: 70, high: 115, low: 60 },
  { x: '2016-01-21', open: 90, close: 100, high: 131, low: 90 },
  { x: '2016-01-22', open: 70, close: 80, high: 100, low: 80 },
  { x: '2016-01-23', open: 80, close: 90, high: 95, low: 80 },
  { x: '2016-01-24', open: 75, close: 54, high: 80, low: 40 },
  { x: '2016-01-25', open: 53, close: 23, high: 80, low: 14 },
  { x: '2016-01-26', open: 90, close: 76, high: 140, low: 47 },
  { x: '2016-01-27', open: 40, close: 60, high: 187, low: 87 },
  { x: '2016-01-28', open: 64, close: 80, high: 67, low: 73 },
  { x: '2016-01-29', open: 52, close: 67, high: 85, low: 40 },
];

const networkData = [
  {
    title: strings.networks,
    data: [
      {
        networkName: 'Mainnet',
        description: 'Production network for live trading',
      },
      {
        networkName: 'Testnet',
        description: 'Test network for development and testing',
      },
    ],
  },
];


export {
  GenderData,
  ProfileSetting,
  question5Data,
  yesAndNoData,
  WorkTypeData,
  countryData,
  houseStatusData,
  termsAndConditionData,
  inviteFriendData,
  myRewardsData,
  helperCategoryData,
  helperData,
  contactUsData,
  languageData,
  aboutOtradeData,
  moreData,
  listedStockData,
  depositOtradeData,
  WithdrawalOtradeData,
  addBankAccountData,
  accountTypeData,
  fundingActivityData,
  financialTransactionData,
  paymentMethodsData,
  stockCategoryData,
  topMoversData,
  discoverStockData,
  discoverListedStock,
  topStockData,
  myWishlistStockData,
  myStockData,
  stockTimeData,
  spotMarketStats,
  characteristicsData,
  peopleAlsoBoughtData,
  portfolioData,
  newsData,
  buySellCategory,
  notificationData,
  mainChartData,
  sampleDataDates,
  similarStocksData,
  networkData,
};
