export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';

// Leaderboard types
export const SET_LEADERBOARD_DATA = 'SET_LEADERBOARD_DATA';
export const SET_LEADERBOARD_LOADING = 'SET_LEADERBOARD_LOADING';
export const SET_LEADERBOARD_ERROR = 'SET_LEADERBOARD_ERROR';
export const SET_USER_STATS = 'SET_USER_STATS';
